from django.db import models

# Create your models here.

class Flight(models.Model):
    Year=models.BigIntegerField(null=True, blank=True)
    Quarter=models.BigIntegerField(null=True, blank=True)
    Month=models.BigIntegerField(null=True, blank=True)
    DayofMonth=models.BigIntegerField(null=True, blank=True)
    DayOfWeek=models.BigIntegerField(null=True, blank=True)
    #FlightDate=models.CharField(max_length=25, null=True, blank=True)
    #Reporting_Airline=models.CharField(max_length=25, null=True, blank=True)
    #DOT_ID_Reporting_Airline=models.BigIntegerField(null=True, blank=True)
    #IATA_CODE_Reporting_Airline=models.CharField(max_length=25, null=True, blank=True)
    #Tail_Number=models.CharField(max_length=25, null=True, blank=True)
    #Flight_Number_Reporting_Airline=models.BigIntegerField(null=True, blank=True)
    #OriginAirportID=models.BigIntegerField(null=True, blank=True)
    #OriginAirportSeqID=models.BigIntegerField(null=True, blank=True)
    #OriginCityMarketID=models.BigIntegerField(null=True, blank=True)
    Origin=models.CharField(max_length=25, null=True, blank=True)
    OriginCityName=models.CharField(max_length=25, null=True, blank=True)
    OriginState=models.CharField(max_length=25, null=True, blank=True)
    #OriginStateFips=models.BigIntegerField(null=True, blank=True)
    OriginStateName=models.CharField(max_length=25, null=True, blank=True)
    #OriginWac=models.BigIntegerField(null=True, blank=True)
    #DestAirportID=models.BigIntegerField(null=True, blank=True)
    #DestAirportSeqID=models.BigIntegerField(null=True, blank=True)
    #DestCityMarketID=models.BigIntegerField(null=True, blank=True)
    Dest=models.CharField(max_length=25, null=True, blank=True)
    DestCityName=models.CharField(max_length=25, null=True, blank=True)
    DestState=models.CharField(max_length=25, null=True, blank=True)
    #DestStateFips=models.BigIntegerField(null=True, blank=True)
    DestStateName=models.CharField(max_length=25, null=True, blank=True)
    #DestWac=models.BigIntegerField(null=True, blank=True)
    CRSDepTime=models.BigIntegerField(null=True, blank=True)
    DepTime=models.BigIntegerField(null=True, blank=True)
    DepDelay=models.FloatField(null=True, blank=True)
    DepDelayMinutes=models.FloatField(null=True, blank=True)
    DepDel15=models.FloatField(null=True, blank=True)
    DepartureDelayGroups=models.BigIntegerField(null=True, blank=True)
    DepTimeBlk=models.CharField(max_length=25, null=True, blank=True)
    #TaxiOut=models.FloatField(null=True, blank=True)
    #WheelsOff=models.BigIntegerField(null=True, blank=True)
    #WheelsOn=models.BigIntegerField(null=True, blank=True)
    #TaxiIn=models.FloatField(null=True, blank=True)
    #CRSArrTime=models.BigIntegerField(null=True, blank=True)
    ArrTime=models.BigIntegerField(null=True, blank=True)
    ArrDelay=models.FloatField(null=True, blank=True)
    ArrDelayMinutes=models.FloatField(null=True, blank=True)
    #ArrDel15=models.FloatField(null=True, blank=True)
    ArrivalDelayGroups=models.BigIntegerField(null=True, blank=True)
    ArrTimeBlk=models.CharField(max_length=25, null=True, blank=True)
    Cancelled=models.FloatField(null=True, blank=True)
    CancellationCode=models.CharField(max_length=25, null=True, blank=True)
    Diverted=models.FloatField(null=True, blank=True)
    #CRSElapsedTime=models.FloatField(null=True, blank=True)
    #ActualElapsedTime=models.FloatField(null=True, blank=True)
    #AirTime=models.FloatField(null=True, blank=True)
    Flights=models.FloatField(null=True, blank=True)
    Distance=models.FloatField(null=True, blank=True)
    DistanceGroup=models.BigIntegerField(null=True, blank=True)
    CarrierDelay=models.CharField(max_length=25, null=True, blank=True)
    WeatherDelay=models.CharField(max_length=25, null=True, blank=True)
    NASDelay=models.CharField(max_length=25, null=True, blank=True)
    SecurityDelay=models.CharField(max_length=25, null=True, blank=True)
    LateAircraftDelay=models.CharField(max_length=25, null=True, blank=True)
    #FirstDepTime=models.CharField(max_length=25, null=True, blank=True)
    #TotalAddGTime=models.CharField(max_length=25, null=True, blank=True)
    #LongestAddGTime=models.CharField(max_length=25, null=True, blank=True)
    #DivAirportLandings=models.BigIntegerField(null=True, blank=True)
    #DivReachedDest=models.CharField(max_length=25, null=True, blank=True)
    #DivActualElapsedTime=models.CharField(max_length=25, null=True, blank=True)
    #DivArrDelay=models.CharField(max_length=25, null=True, blank=True)
    #DivDistance=models.CharField(max_length=25, null=True, blank=True)
    #Div1Airport=models.CharField(max_length=25, null=True, blank=True)
    #Div1AirportID=models.CharField(max_length=25, null=True, blank=True)
    #Div1AirportSeqID=models.CharField(max_length=25, null=True, blank=True)
    #Div1WheelsOn=models.CharField(max_length=25, null=True, blank=True)
    #Div1TotalGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div1LongestGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div1WheelsOff=models.CharField(max_length=25, null=True, blank=True)
    #Div1TailNum=models.CharField(max_length=25, null=True, blank=True)
    #Div2Airport=models.CharField(max_length=25, null=True, blank=True)
    #Div2AirportID=models.CharField(max_length=25, null=True, blank=True)
    #Div2AirportSeqID=models.CharField(max_length=25, null=True, blank=True)
    #Div2WheelsOn=models.CharField(max_length=25, null=True, blank=True)
    #Div2TotalGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div2LongestGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div2WheelsOff=models.CharField(max_length=25, null=True, blank=True)
    #Div2TailNum=models.CharField(max_length=25, null=True, blank=True)
    #Div3Airport=models.CharField(max_length=25, null=True, blank=True)
    #Div3AirportID=models.CharField(max_length=25, null=True, blank=True)
    #Div3AirportSeqID=models.CharField(max_length=25, null=True, blank=True)
    #Div3WheelsOn=models.CharField(max_length=25, null=True, blank=True)
    #Div3TotalGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div3LongestGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div3WheelsOff=models.CharField(max_length=25, null=True, blank=True)
    #Div3TailNum=models.CharField(max_length=25, null=True, blank=True)
    #Div4Airport=models.CharField(max_length=25, null=True, blank=True)
    #Div4AirportID=models.CharField(max_length=25, null=True, blank=True)
    #Div4AirportSeqID=models.CharField(max_length=25, null=True, blank=True)
    #Div4WheelsOn=models.CharField(max_length=25, null=True, blank=True)
    #Div4TotalGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div4LongestGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div4WheelsOff=models.CharField(max_length=25, null=True, blank=True)
    #Div4TailNum=models.CharField(max_length=25, null=True, blank=True)
    #Div5Airport=models.CharField(max_length=25, null=True, blank=True)
    #Div5AirportID=models.CharField(max_length=25, null=True, blank=True)
    #Div5AirportSeqID=models.CharField(max_length=25, null=True, blank=True)
    #Div5WheelsOn=models.CharField(max_length=25, null=True, blank=True)
    #Div5TotalGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div5LongestGTime=models.CharField(max_length=25, null=True, blank=True)
    #Div5WheelsOff=models.CharField(max_length=25, null=True, blank=True)
    #Div5TailNum=models.CharField(max_length=25, null=True, blank=True)