# Generated by Django 4.1.7 on 2023-03-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_flight_actualelapsedtime_alter_flight_airtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='ActualElapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='AirTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ArrDel15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ArrDelay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ArrDelayMinutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ArrTime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ArrivalDelayGroups',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CRSArrTime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CRSDepTime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='CRSElapsedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Cancelled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DOT_ID_Reporting_Airline',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DayOfWeek',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DayofMonth',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DepDel15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DepDelay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DepDelayMinutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DepTime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DepartureDelayGroups',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DestAirportID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DestAirportSeqID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DestCityMarketID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DestStateFips',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DestWac',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DistanceGroup',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='DivAirportLandings',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Diverted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_Number_Reporting_Airline',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flights',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Month',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='OriginAirportID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='OriginAirportSeqID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='OriginCityMarketID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='OriginStateFips',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='OriginWac',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Quarter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TaxiIn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='TaxiOut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='WheelsOff',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='WheelsOn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Year',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
