# Generated by Django 4.1.7 on 2023-03-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_flight_arrtimeblk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='CancellationCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
