# Generated by Django 4.1.7 on 2023-03-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='connections',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.airport'),
        ),
        migrations.AddField(
            model_name='airport',
            name='iata',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
